branch-defaults:
  master:
    environment: node-chat-api-env
    group_suffix: null
global:
  application_name: Sockets-Practice
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: eu-north-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
